#!/bin/bash

# Script para ajudar na configuração do GitHub Token
echo "🔧 === CONFIGURAÇÃO DO GITHUB TOKEN ==="
echo ""
echo "Para configurar o sistema de relatórios com sincronização GitHub:"
echo ""
echo "1. Acesse: https://github.com/settings/tokens"
echo "2. Clique em 'Generate new token (classic)'"
echo "3. Configure:"
echo "   - Note: 'Sistema de Relatórios OM30'"
echo "   - Expiration: 90 days (ou conforme sua política)"
echo "   - Scopes: ✅ repo (Full control of private repositories)"
echo ""
echo "4. Copie o token gerado (ex: ghp_xxxxxxxxxxxxxxxxxxxx)"
echo "5. Cole no arquivo config.js na linha GITHUB_TOKEN"
echo ""
echo "6. Verifique se o repositório está correto:"
echo "   GITHUB_REPO: 'Marcelo-OM30/opsreport'"
echo ""
echo "7. Teste a configuração abrindo o site e clicando em 'Config' > 'Diagnóstico Completo'"
echo ""
echo "💡 DICAS:"
echo "   - Use tokens classic (não fine-grained) para melhor compatibilidade"
echo "   - Se der erro 401, verifique se o token foi copiado corretamente"
echo "   - Se der erro 404, verifique se o repositório existe e está acessível"
echo ""
echo "🔒 SEGURANÇA:"
echo "   - NUNCA compartilhe o token em canais públicos"
echo "   - O arquivo config.js está no .gitignore (não será commitado)"
echo "   - Revogue tokens antigos se não estiver usando"
echo ""
echo "Para testar manualmente:"
echo "curl -H \"Authorization: token SEU_TOKEN\" https://api.github.com/user"
echo ""
